on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Build job
  build:
    Vala:
      strategy:
        matrix:
          node-version: [16.x, 18.x]
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install the dependencies
          run: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get update -y
            sudo apt-get install -y --no-install-recommends software-properties-common
            sudo add-apt-repository -y ppa:vala-team/daily
            sudo apt-get update -y
            sudo apt-get install \
            -y \
            --no-install-recommends \
            gcc \
            libgee-0.8-dev \
            git \
            libguestfs-gobject-dev \
            libtemplate-glib-1.0-dev \
            libvaladoc-0.58-dev \
            meson \
            ninja-build \
            unzip \
            valac \
            valadoc \
            wget \
            xsltproc \
            make \

        - name: Build the documentation
          run: |
            task/build GENERATOR_OPTS="" \
            && PRESET=core task/run

        - name: Build website assets with Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
          run: |
            npm ci && npm run build

        - name: Upload GitHub Pages artifiact
          inputs:
            path: "valadoc.org"

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
